### ISSUE TITLE
Move to official org?

### ISSUE THREAD

**Issue by zenorocha** [dracula/ulauncher#1]
Hey @cweagans,

This is Zeno, creator of Dracula. I just this found repo, good job on that!

I'm wondering if you would like to have this become an official theme in our [Dracula organization](https://github.com/dracula)?

Let me know what you think.

**Comment by cweagans** [comment]
I actually opened an issue for this a while back and never finished the process. https://github.com/dracula/dracula-theme/issues/315

I'll go ahead and move it.

**Comment by cweagans** [comment]
(repo has been moved)

**Comment by zenorocha** [comment]
Thanks!
